services:
  mote:
    image: ghcr.io/empriselab/mote-ros-noetic:latest
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:8765"   # Foxglove Bridge WebSocket (connect Foxglove Studio to ws://<host>:8765)
      - "11311:11311" # ROS Master URI (allows host-side ros CLI tools to connect)
    environment:
      # Required
      ROBOT_IP: ${ROBOT_IP}
      PYTHONUNBUFFERED: "1"
